// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSV.EF.Contexts;

#nullable disable

namespace QLSV.Migrations
{
    [DbContext(typeof(QlsvContext))]
    partial class QlsvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLSV.EF.Models.KetQua", b =>
                {
                    b.Property<int>("Mamon")
                        .HasColumnType("int")
                        .HasColumnName("MAMON");

                    b.Property<string>("Masv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASV");

                    b.Property<double>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("DIEM");

                    b.HasKey("Mamon", "Masv")
                        .HasName("PK__KetQua__ED71C127844DD13D");

                    b.HasIndex("Masv");

                    b.ToTable("KetQua", (string)null);
                });

            modelBuilder.Entity("QLSV.EF.Models.Khoa", b =>
                {
                    b.Property<int>("Makhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKHOA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makhoa"));

                    b.Property<string>("Tenkhoa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENKHOA");

                    b.HasKey("Makhoa")
                        .HasName("PK__Khoa__22F41770E09FAFA8");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("QLSV.EF.Models.MonHoc", b =>
                {
                    b.Property<int>("Mamon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAMON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mamon"));

                    b.Property<string>("Tenmon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENMON");

                    b.HasKey("Mamon")
                        .HasName("PK__MonHoc__7B73E9850C403AF5");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("QLSV.EF.Models.Nganh", b =>
                {
                    b.Property<int>("Manganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANGANH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manganh"));

                    b.Property<int>("Makhoa")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOA");

                    b.Property<string>("Tennganh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENNGANH");

                    b.HasKey("Manganh")
                        .HasName("PK__Nganh__934F1CE20A24836A");

                    b.HasIndex("Makhoa");

                    b.ToTable("Nganh", (string)null);
                });

            modelBuilder.Entity("QLSV.EF.Models.SinhVien", b =>
                {
                    b.Property<string>("Masv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASV");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DIACHI");

                    b.Property<byte>("Gioitinh")
                        .HasColumnType("tinyint")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hosv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("HOSV");

                    b.Property<int>("Manganh")
                        .HasColumnType("int")
                        .HasColumnName("MANGANH");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Noisinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NOISINH");

                    b.Property<string>("Tensv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TENSV");

                    b.HasKey("Masv")
                        .HasName("PK__SinhVien__60228A28A9D66813");

                    b.HasIndex("Manganh");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QLSV.EF.Models.KetQua", b =>
                {
                    b.HasOne("QLSV.EF.Models.MonHoc", "MamonNavigation")
                        .WithMany("KetQuas")
                        .HasForeignKey("Mamon")
                        .IsRequired()
                        .HasConstraintName("FK__KetQua__MAMON__4222D4EF");

                    b.HasOne("QLSV.EF.Models.SinhVien", "MasvNavigation")
                        .WithMany("KetQuas")
                        .HasForeignKey("Masv")
                        .IsRequired()
                        .HasConstraintName("FK__KetQua__MASV__4316F928");

                    b.Navigation("MamonNavigation");

                    b.Navigation("MasvNavigation");
                });

            modelBuilder.Entity("QLSV.EF.Models.Nganh", b =>
                {
                    b.HasOne("QLSV.EF.Models.Khoa", "MakhoaNavigation")
                        .WithMany("Nganhs")
                        .HasForeignKey("Makhoa")
                        .IsRequired()
                        .HasConstraintName("FK__Nganh__MAKHOA__398D8EEE");

                    b.Navigation("MakhoaNavigation");
                });

            modelBuilder.Entity("QLSV.EF.Models.SinhVien", b =>
                {
                    b.HasOne("QLSV.EF.Models.Nganh", "ManganhNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("Manganh")
                        .IsRequired()
                        .HasConstraintName("FK__SinhVien__MANGAN__3C69FB99");

                    b.Navigation("ManganhNavigation");
                });

            modelBuilder.Entity("QLSV.EF.Models.Khoa", b =>
                {
                    b.Navigation("Nganhs");
                });

            modelBuilder.Entity("QLSV.EF.Models.MonHoc", b =>
                {
                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("QLSV.EF.Models.Nganh", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QLSV.EF.Models.SinhVien", b =>
                {
                    b.Navigation("KetQuas");
                });
#pragma warning restore 612, 618
        }
    }
}
